// This file was generated by Prisma and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';
import dotenv from 'dotenv';

dotenv.config({
  path: '.env',
});
export default defineConfig({
  schema: 'prisma/schema.prisma',
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    // no runtime check here, so `prisma generate` won't fail
    url: process.env.DATABASE_URL ?? 'postgres://placeholder',
  },
});
